name: CI

on: [ push, pull_request ]

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
    - name: linux-x64
      run: ./build-linux-x86_64.sh
    - uses: actions/upload-artifact@v3
      with:
        name: linux
        path: |
          native-linux-x86_64/RuneLite.AppImage
        if-no-files-found: error